name: Bygg dokumentasjon

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v4
            - name: Install Quarto
              uses: quarto-dev/quarto-actions/setup@v2
            - name: Render project
              uses: quarto-dev/quarto-actions/render@v2
              with:
                path: doc/
            - name: Last opp til Datamarkedsplassen
              uses: navikt/story-upload@v1
              with:
                id: a02b3e56-a407-4dad-96c9-8b4425ea3906
                dir: doc/
                team_token: ${{ secrets.TEAM_TOKEN }}
                env: prod
                public: false
            - name: Upload to cache
              uses: actions/upload-artifact@v4
              with:
                name: doc
                path: doc/*.html
                overwrite: true
